language: swift
xcode_project: Community.xcworkspace
xcode_scheme: CommunityUITests
osx_image: xcode9.2
xcode_sdk: iphonesimulato11.0
script: bundle exec rake

before_install:
  - curl http://curl.haxx.se/ca/cacert.pem -o /usr/local/share/cacert.pem
  - gem install bundler --no-ri --no-rdoc

install:
  - bundle install --without=documentation

jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - fastlane scan -s CommunityUITests 
