language: swift
xcode_project: Community.xcworkspace
xcode_scheme: CommunityUITests
osx_image: xcode9.2
xcode_sdk: iphonesimulato11.0

jobs:
  include:
    - stage: Swiflint
      script:
        - fastlane lint

    - stage: CodeCoverage
      script:
        - fastlane report_tests

