language: swift
xcode_project: Community.xcworkspace
xcode_scheme: CommunityUITests
osx_image: xcode9.2
xcode_sdk: iphonesimulato11.0

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather

jobs:
  include:
    - stage: Swiflint
      script:
        - ./Pods/SwiftLint/swiftlint --reporter junit

    - stage: XCTest
      script:
        - fastlane scan -s CommunityUITests 
